osx_image: xcode10
language: swift
xcode_workspace: Pollo.xcworkspace
xcode_scheme: PolloTests
install: pod update
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace Pollo.xcworkspace -scheme PolloTests CODE_SIGNING_REQUIRED=NO > /dev/null
